// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package trainproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Location struct {
	// @inject_tag: xml:"crs"
	CRS string `protobuf:"bytes,1,opt,name=CRS" json:"CRS,omitempty" xml:"crs"`
	// @inject_tag: xml:"locationName"
	Name                 string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty" xml:"locationName"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ebc631f04b9a0cc0, []int{0}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetCRS() string {
	if m != nil {
		return m.CRS
	}
	return ""
}

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BoardService struct {
	// @inject_tag: xml:"std"
	ScheduledDeparture string `protobuf:"bytes,1,opt,name=ScheduledDeparture" json:"ScheduledDeparture,omitempty" xml:"std"`
	// @inject_tag: xml:"etd"
	EstimatedDeparture string `protobuf:"bytes,2,opt,name=EstimatedDeparture" json:"EstimatedDeparture,omitempty" xml:"etd"`
	// @inject_tag: xml:"sta"
	ScheduledArrival string `protobuf:"bytes,3,opt,name=ScheduledArrival" json:"ScheduledArrival,omitempty" xml:"sta"`
	// @inject_tag: xml:"eta"
	EstimatedArrival string `protobuf:"bytes,4,opt,name=EstimatedArrival" json:"EstimatedArrival,omitempty" xml:"eta"`
	// @inject_tag: xml:"platform"
	Platform int32 `protobuf:"varint,5,opt,name=Platform" json:"Platform,omitempty" xml:"platform"`
	// @inject_tag: xml:"operator"
	Operator string `protobuf:"bytes,6,opt,name=Operator" json:"Operator,omitempty" xml:"operator"`
	// @inject_tag: xml:"operatorCode"
	OperatorCode string `protobuf:"bytes,7,opt,name=OperatorCode" json:"OperatorCode,omitempty" xml:"operatorCode"`
	// @inject_tag: xml:"serviceType"
	ServiceType string `protobuf:"bytes,8,opt,name=ServiceType" json:"ServiceType,omitempty" xml:"serviceType"`
	// @inject_tag: xml:"serviceID"
	ServiceID string `protobuf:"bytes,9,opt,name=ServiceID" json:"ServiceID,omitempty" xml:"serviceID"`
	// @inject_tag: xml:"origin>location"
	Origin *Location `protobuf:"bytes,10,opt,name=Origin" json:"Origin,omitempty" xml:"origin>location"`
	// @inject_tag: xml:"destination>location"
	Destination          *Location `protobuf:"bytes,11,opt,name=Destination" json:"Destination,omitempty" xml:"destination>location"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BoardService) Reset()         { *m = BoardService{} }
func (m *BoardService) String() string { return proto.CompactTextString(m) }
func (*BoardService) ProtoMessage()    {}
func (*BoardService) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ebc631f04b9a0cc0, []int{1}
}
func (m *BoardService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoardService.Unmarshal(m, b)
}
func (m *BoardService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoardService.Marshal(b, m, deterministic)
}
func (dst *BoardService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoardService.Merge(dst, src)
}
func (m *BoardService) XXX_Size() int {
	return xxx_messageInfo_BoardService.Size(m)
}
func (m *BoardService) XXX_DiscardUnknown() {
	xxx_messageInfo_BoardService.DiscardUnknown(m)
}

var xxx_messageInfo_BoardService proto.InternalMessageInfo

func (m *BoardService) GetScheduledDeparture() string {
	if m != nil {
		return m.ScheduledDeparture
	}
	return ""
}

func (m *BoardService) GetEstimatedDeparture() string {
	if m != nil {
		return m.EstimatedDeparture
	}
	return ""
}

func (m *BoardService) GetScheduledArrival() string {
	if m != nil {
		return m.ScheduledArrival
	}
	return ""
}

func (m *BoardService) GetEstimatedArrival() string {
	if m != nil {
		return m.EstimatedArrival
	}
	return ""
}

func (m *BoardService) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *BoardService) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *BoardService) GetOperatorCode() string {
	if m != nil {
		return m.OperatorCode
	}
	return ""
}

func (m *BoardService) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *BoardService) GetServiceID() string {
	if m != nil {
		return m.ServiceID
	}
	return ""
}

func (m *BoardService) GetOrigin() *Location {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *BoardService) GetDestination() *Location {
	if m != nil {
		return m.Destination
	}
	return nil
}

type DepartureBoard struct {
	GeneratedAt          string          `protobuf:"bytes,1,opt,name=GeneratedAt" json:"GeneratedAt,omitempty"`
	Location             string          `protobuf:"bytes,2,opt,name=Location" json:"Location,omitempty"`
	CRS                  string          `protobuf:"bytes,3,opt,name=CRS" json:"CRS,omitempty"`
	HasPlatform          bool            `protobuf:"varint,4,opt,name=HasPlatform" json:"HasPlatform,omitempty"`
	Services             []*BoardService `protobuf:"bytes,5,rep,name=Services" json:"Services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DepartureBoard) Reset()         { *m = DepartureBoard{} }
func (m *DepartureBoard) String() string { return proto.CompactTextString(m) }
func (*DepartureBoard) ProtoMessage()    {}
func (*DepartureBoard) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ebc631f04b9a0cc0, []int{2}
}
func (m *DepartureBoard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartureBoard.Unmarshal(m, b)
}
func (m *DepartureBoard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartureBoard.Marshal(b, m, deterministic)
}
func (dst *DepartureBoard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartureBoard.Merge(dst, src)
}
func (m *DepartureBoard) XXX_Size() int {
	return xxx_messageInfo_DepartureBoard.Size(m)
}
func (m *DepartureBoard) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartureBoard.DiscardUnknown(m)
}

var xxx_messageInfo_DepartureBoard proto.InternalMessageInfo

func (m *DepartureBoard) GetGeneratedAt() string {
	if m != nil {
		return m.GeneratedAt
	}
	return ""
}

func (m *DepartureBoard) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *DepartureBoard) GetCRS() string {
	if m != nil {
		return m.CRS
	}
	return ""
}

func (m *DepartureBoard) GetHasPlatform() bool {
	if m != nil {
		return m.HasPlatform
	}
	return false
}

func (m *DepartureBoard) GetServices() []*BoardService {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "trainproto.Location")
	proto.RegisterType((*BoardService)(nil), "trainproto.BoardService")
	proto.RegisterType((*DepartureBoard)(nil), "trainproto.DepartureBoard")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_ebc631f04b9a0cc0) }

var fileDescriptor_api_ebc631f04b9a0cc0 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xa9, 0xdd, 0x66, 0x7b, 0x3a, 0x64, 0x1c, 0xbc, 0x08, 0xe2, 0x45, 0xe9, 0x55, 0x11,
	0x29, 0x32, 0xc5, 0xfb, 0xb9, 0x89, 0x0a, 0xe2, 0xa4, 0xf3, 0x05, 0xe2, 0x1a, 0x35, 0xb0, 0x35,
	0x25, 0xcd, 0x06, 0xbe, 0x99, 0x8f, 0xe0, 0x63, 0x49, 0xb2, 0x36, 0x8b, 0x6e, 0x78, 0x77, 0xf2,
	0xff, 0x5f, 0x4f, 0x93, 0xf3, 0x1f, 0x08, 0x69, 0xc5, 0xb3, 0x4a, 0x0a, 0x25, 0x10, 0x94, 0xa4,
	0xbc, 0x34, 0x75, 0x72, 0x01, 0xc1, 0xa3, 0x98, 0x53, 0xc5, 0x45, 0x89, 0x03, 0xf0, 0xc7, 0xf9,
	0x8c, 0x78, 0xb1, 0x97, 0x86, 0xb9, 0x2e, 0x11, 0xa1, 0xf3, 0x44, 0x97, 0x8c, 0x1c, 0x18, 0xc9,
	0xd4, 0xc9, 0xb7, 0x0f, 0xfd, 0x1b, 0x41, 0x65, 0x31, 0x63, 0x72, 0xcd, 0xe7, 0x0c, 0x33, 0xc0,
	0xd9, 0xfc, 0x83, 0x15, 0xab, 0x05, 0x2b, 0x26, 0xac, 0xa2, 0x52, 0xad, 0x24, 0x6b, 0xba, 0xec,
	0x71, 0x34, 0x7f, 0x5b, 0x2b, 0xbe, 0xa4, 0xca, 0xe5, 0x37, 0xbf, 0xd8, 0xe3, 0xe0, 0x19, 0x0c,
	0x6c, 0x97, 0x91, 0x94, 0x7c, 0x4d, 0x17, 0xc4, 0x37, 0xf4, 0x8e, 0xae, 0x59, 0xdb, 0xa1, 0x65,
	0x3b, 0x1b, 0xf6, 0xaf, 0x8e, 0x27, 0x10, 0x3c, 0x2f, 0xa8, 0x7a, 0x13, 0x72, 0x49, 0xba, 0xb1,
	0x97, 0x76, 0x73, 0x7b, 0xd6, 0xde, 0xb4, 0x62, 0x92, 0x2a, 0x21, 0x49, 0xcf, 0x7c, 0x6f, 0xcf,
	0x98, 0x40, 0xbf, 0xad, 0xc7, 0xa2, 0x60, 0xe4, 0xd0, 0xf8, 0xbf, 0x34, 0x8c, 0x21, 0x6a, 0xc6,
	0xf3, 0xf2, 0x59, 0x31, 0x12, 0x18, 0xc4, 0x95, 0xf0, 0x14, 0xc2, 0xe6, 0xf8, 0x30, 0x21, 0xa1,
	0xf1, 0xb7, 0x02, 0x9e, 0x43, 0x6f, 0x2a, 0xf9, 0x3b, 0x2f, 0x09, 0xc4, 0x5e, 0x1a, 0x0d, 0x8f,
	0xb3, 0x6d, 0x66, 0x59, 0x1b, 0x58, 0xde, 0x30, 0x78, 0x0d, 0xd1, 0x84, 0xd5, 0x8a, 0x97, 0x46,
	0x26, 0xd1, 0x3f, 0x9f, 0xb8, 0x60, 0xf2, 0xe5, 0xc1, 0x91, 0x9d, 0xb3, 0xc9, 0x54, 0x5f, 0xfc,
	0x8e, 0x95, 0xfa, 0x25, 0xac, 0x18, 0xa9, 0x26, 0x45, 0x57, 0xd2, 0xa3, 0x69, 0xbb, 0x35, 0xa1,
	0xed, 0x6c, 0x90, 0xbf, 0xdd, 0xa0, 0x18, 0xa2, 0x7b, 0x5a, 0xdb, 0x39, 0xeb, 0x2c, 0x82, 0xdc,
	0x95, 0xf0, 0x0a, 0x82, 0xe6, 0xdd, 0x35, 0xe9, 0xc6, 0x7e, 0x1a, 0x0d, 0x89, 0x7b, 0x73, 0x77,
	0xd5, 0x72, 0x4b, 0xbe, 0xf6, 0x8c, 0x7b, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x79, 0x90, 0xaf,
	0x17, 0xd7, 0x02, 0x00, 0x00,
}
